### ISSUE TITLE
Binary.lua

### ISSUE THREAD

**Issue by vibecodingengine** [1adrianb/bnn.torch#1]
In Binary.lua:
This piece of code:
`    
self.gradInput[input:ge(-1)] = 0
self.gradInput[input:le(-1)] = 0
`
I think it should be 
`    
self.gradInput[input:ge(1)] = 0
self.gradInput[input:le(-1)] = 0
`
I'm not familiar with lua, correct me if I'm wrong.

**Comment by 1adrianb** [comment]
You are right. Thanks a lot for catching this.
